# Generated by Django 2.1.5 on 2019-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_system_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsreport',
            name='cached_insights',
            field=models.TextField(null=True),
        ),
    ]
